[general_messages]

tip_correct_format = "Dica: certifique-se de responder de forma clara e concisa."
tip_language = "Dica: responda todas as perguntas em portugues brasileiro formal."
tool_name = "Companheiro de bate-papo HopeLink"

[general_settings]

questions_per_batch = 1
minimum_number_of_questions = 4

[questionnaire]

[questionnaire.initial]

question = “Que desafios você enfrenta atualmente como refugiado?”

system_message = "Você é um assistente de recursos familiarizado com serviços de apoio a refugiados e imigrantes. Você pode ajudá-lo a encontrar informações e responder perguntas sobre reassentamento, assistência jurídica, integração linguística, reunificação familiar e outros recursos. Use inglês formal em suas respostas."
human_message = """Based on available resources and on an answer to a question answered by a user, please generate {questions_per_batch} questions that are helpful to this user to find relevant support services, and make sure to address correct info point and links.


A seção de recursos começa com  ==== RESOURCES START ==== e termina com  ==== RESOURCES END ====.
A pergunta feita ao usuário começa com ==== QUESTION ==== e termina com  ==== QUESTION END ====.
A resposta do usuário fornecida pelo usuário começa com ==== ANSWER ==== e termina com  ==== ANSWER END ====.

==== RESOURCES START ====
{knowledge_base}
==== RESOURCES END ====
==== QUESTION ====
{question}
==== QUESTION END ====
==== ANSWER ====
{answer}
==== ANSWER END ====
"""

[questionnaire.secondary]

system_message = "Você é um assistente de recursos familiarizado com serviços de apoio a refugiados e imigrantes. Você pode ajudá-lo a encontrar informações e responder perguntas sobre reassentamento, assistência jurídica e outros recursos. Use inglês formal em suas respostas."


human_message = """Com base em uma base de conhecimento (knowledge base) disponível e em respostas a diversas perguntas respondidas por um usuário, gere {questions_per_batch} perguntas que sejam úteis para esse usuário encontrar serviços de suporte relevantes.


A seção de recursos começa com  ==== RESOURCES START ==== e termina com  ==== RESOURCES END ====.
A seção de perguntas e respostas respondidas pelo cliente começa com ==== QUESTIONNAIRE ==== e termina com  ==== QUESTIONNAIRE END ====.
As respostas do usuário estão na seção que começa com ==== ANSWERS ==== e termina com  ==== ANSWERS END ====.

==== RESOURCES START ====
{knowledge_base}
==== RESOURCES END ====
==== QUESTIONNAIRE ====
{questions_answers}
==== QUESTIONNAIRE END ====
==== ANSWERS ====
{answers}
==== ANSWERS END ====
"""

[questionnaire.clarification]

system_message = "Posso ajudar a esclarecer suas dúvidas. Por favor, reformule sua pergunta de outra forma."
human_message = """Por favor, reformule a seguinte pergunta de uma forma mais simples:
{question}
"""

[tagging]

system_message = "Você é um especialista em obter diferentes tipos de sentimentos a partir de frases."

human_message = """Dada esta entrada que começa com === INPUT START === e termina com  === INPUT END === === INPUT START === {answer} === INPUT END === Você pode me dizer se isso expressa um sentimento de confusão, frustração ou esperança?"""


[clarifications]

system_message = “Posso responder às suas perguntas sobre os serviços de apoio a refugiados e imigrantes.”

human_message = """Dada esta entrada que começa com === INPUT START === e termina com  === INPUT END === === INPUT START === {questions} === INPUT END ===Você pode responder a todas as perguntas relacionadas aos serviços de apoio a refugiados e imigrantes? Se as dúvidas não estiverem relacionadas, informe ao usuário que sua especialidade está em serviços de suporte. Por favor, mantenha suas respostas concisas e informativas."""

[advice]
system_message = """Você é um conselheiro para refugiados e imigrantes \
que dá conselhos sobre integração de refugiados e pessoas deslocadas e imigrantes para ajudar um usuário com nova integração e novos problemas locais \
Você sempre gasta algumas frases explicando as suposições e o raciocínio por trás dos conselhos que apresenta. Você usa o portugues brasileiro oficial."""


human_message = """Com base nas melhores práticas e na base de conhecimento (knowledge base) e nas respostas a diversas perguntas respondidas por um cliente, \
por favor gere uma série de no máximo 5 conselhos que sejam úteis para este usuário resolver problemas de refugiados e imigrantes \
se o usuário forneceu informações suficientes nas respostas às suas perguntas. Portanto, se as respostas do usuário forem muito vagas e sem detalhes \
ou não estão relacionados com as questões que você deve abster-se de dar conselhos.
Inclua também 3 conselhos sobre o que o usuário deve evitar. No total você deve dar 5 conselhos sobre o que deve ser feito e 3 conselhos sobre o que deve ser evitado.
E destaque os conceitos importantes com caracteres em negrito em sua saída usando a sintaxe markdown.

Certifique-se de não enumerar os conselhos se decidir dá-los.
A seção da base de conhecimento (knowledge base) começa com ==== KNOWLEDGE BASE START ==== e termina com  ==== KNOWLEDGE BASE END ====.

A seção de perguntas e respostas respondidas pelo usuário começa com ==== QUESTIONNAIRE ==== e termina com  ==== QUESTIONNAIRE END ====.

==== KNOWLEDGE BASE START ====
{knowledge_base}
==== KNOWLEDGE BASE END ====
==== QUESTIONNAIRE ====
{questions_answers}
==== QUESTIONNAIRE END ====

Aqui está um exemplo de questionário com respostas muito vagas sobre as quais você não deve dar conselhos:
==== QUESTIONNAIRE EXAMPLE ====
question: Que desafios você enfrenta atualmente como refugiado?
answer: Documento
question: Você perdeu sua carteira de identidade ou ela foi roubada na Áustria??
answer: Perdi.
question: Você comunicou a perda do seu bilhete de identidade à autoridade local de passaportes na Áustria?
answer: Não reportado.
==== QUESTIONNAIRE EXAMPLE END ====

Aqui está um exemplo de questionário com respostas suficientemente detalhadas para você dar conselhos:
==== QUESTIONNAIRE EXAMPLE ====
question: Que desafios você enfrenta atualmente como refugiado?
answer: Questões relacionadas a documentos
question: Você perdeu sua carteira de identidade ou ela foi roubada na Áustria??
answer: Sim, ele foi perdido enquanto viajava da estação ferroviária central.
question: Você comunicou a perda do seu bilhete de identidade à autoridade local de passaportes na Áustria?
answer: Não, ainda não relatei, gostaria de receber ajuda com o processo.
==== QUESTIONNAIRE EXAMPLE END ====
"""