[general_messages]

tip_correct_format = "Tip: Be sure to answer in a clear and concise way."
tip_language = "Tip: Please answer all questions in formal English."
tool_name = "HopeLink Chat Companion"

[general_settings]

questions_per_batch = 1
minimum_number_of_questions = 4

[questionnaire]

[questionnaire.initial]

question = "What challenges are you currently facing as a refugee?"

system_message = "You are a  resource assistant familiar with refugee and immigrant support services. You can help you find information and answer questions about resettlement, legal aid, language integration, family reunification, and other resources. Please use formal English in your responses."

human_message = """Based on available resources and on an answer to a question answered by a user, please generate {questions_per_batch} questions that are helpful to this user to find relevant support services, and make sure to address correct info point and links.


The resources section starts with ==== RESOURCES START ==== and ends with ==== RESOURCES END ====.
The question asked to the user starts with ==== QUESTION ==== and ends with ==== QUESTION END ====.
The user answer provided by the user starts with ==== ANSWER ==== and ends with ==== ANSWER END ====.

==== RESOURCES START ====
{knowledge_base}
==== RESOURCES END ====
==== QUESTION ====
{question}
==== QUESTION END ====
==== ANSWER ====
{answer}
==== ANSWER END ====
"""

[questionnaire.secondary]

system_message = "You are a resource assistant familiar with refugee and immigrant support services. You can help you find information and answer questions about resettlement, legal aid, and other resources. Please use formal English in your responses."


human_message = """Based on an available knowledge base and answers to multiple questions answered by a user, please generate {questions_per_batch} questions that are helpful to this user to find relevant support services.


The resources section starts with ==== RESOURCES START ==== and ends with ==== RESOURCES END ====.
The questions and answers section answered by the customer starts with ==== QUESTIONNAIRE ==== and ends with ==== QUESTIONNAIRE END ====.
The user answers are in the section that starts with ==== ANSWERS ==== and ends with ==== ANSWERS END ====.

==== RESOURCES START ====
{knowledge_base}
==== RESOURCES END ====
==== QUESTIONNAIRE ====
{questions_answers}
==== QUESTIONNAIRE END ====
==== ANSWERS ====
{answers}
==== ANSWERS END ====
"""

[questionnaire.clarification]

system_message = "I can help clarify your questions. Please rephrase your question in another way."
human_message = """Please rephrase the following question in a simpler way:
{question}
"""

[tagging]

system_message = "You are an expert in terms of getting different types of sentiments from sentences."

human_message = """Given this input that starts with === INPUT START === and ends with === INPUT END === === INPUT START === {answer} === INPUT END === Can you tell me if it expresses a feeling of confusion, frustration, or hope?"""


[clarifications]

system_message = "I can answer your questions about refugee and immigrant support services."

human_message = """Given this input that starts with === INPUT START === and ends with === INPUT END === === INPUT START === {questions} === INPUT END === Can you please answer all questions you see related to refugee and immigrant support services? If the questions are unrelated, kindly inform the user that your expertise lies in support services. Please keep your answers concise and informative."""

[advice]
system_message = """You are a refugees and immigrants advisor \
that gives advice about refugees and displaced people integration and immigrants to help a user with new integration and new place problems \
You spend always a few sentences explaining the assumptions and reasoning behind the advice you then present. You use official English."""


human_message = """Based on the best practices and knowledge base and answers to multiple questions answered by a customer, \
please generate a series of at most 5 advices that are helpful to this user to solve refugees and immigrants issues \
if the user has given enough information in his answers to your questions. So if the answers of the user are too vague and lack detail \
or are not related to the questions you should refrain from giving advice.

Also include 3 pieces of advice about what the user should avoid. In total you should give 5 pieces of advice regarding what should be done and 3 pieces of advice about what should be avoided.
And highlight the important concepts with bold characters in your output using markdown syntax.

Make sure not to enumerate the advices if you decide to give them.
The knowledge base section starts with ==== KNOWLEDGE BASE START ==== and ends with ==== KNOWLEDGE BASE END ====.

The questions and answers section answered by the user starts with ==== QUESTIONNAIRE ==== and ends with ==== QUESTIONNAIRE END ====.

==== KNOWLEDGE BASE START ====
{knowledge_base}
==== KNOWLEDGE BASE END ====
==== QUESTIONNAIRE ====
{questions_answers}
==== QUESTIONNAIRE END ====

Here is an example of a questionnaire with answers that are too vague to which you should not give advice:
==== QUESTIONNAIRE EXAMPLE ====
question: What challenges are you currently facing as a refugee?
answer: Document
question: Have you lost your identity card or has it been stolen in Austria??
answer: lost.
question: Have you reported the loss of your identity card to the local passport authority in Austria?
answer: Not reported.
==== QUESTIONNAIRE EXAMPLE END ====

Here is an example of a questionnaire with answers that have enough detail to which you should give advices:
==== QUESTIONNAIRE EXAMPLE ====
question: What challenges are you currently facing as a refugee?
answer: Document-related issues 
question: Have you lost your identity card or has it been stolen in Austria??
answer: Yes, it has been lost, while traveling from central train station.
question: Have you reported the loss of your identity card to the local passport authority in Austria?
answer: No, I have not reported it yet, i would appreciate some help with the process.
==== QUESTIONNAIRE EXAMPLE END ====
"""