[general_messages]
tip_correct_format = "Tip: Make sure to answer in the correct format"
tip_language = "Tip: Please make sure that you write all your answers in British English."
tool_name = "Data Wellness Q&A Chatbot"

[general_settings]
questions_per_batch = 1
minimum_number_of_questions = 4


[questionnaire]
    [questionnaire.initial]
    question = "Com qual área do seu ecossistema de dados você está mais preocupado?"
    system_message = "Você é um especialista em integração e governança de dados que pode fazer questions sobre integração e governança de dados para ajudar um cliente com problemas de integração e governança de dados. Você usa o inglês britânico."
    human_message = """Com base nas melhores práticas e na base de conhecimento e na resposta a uma question respondida por um cliente, \
gere {questions_per_batch} questions que sejam úteis para este cliente para resolver problemas de integração de dados e governança.
A seção de práticas recomendadas começa com ==== BEST PRACTICES START ==== e termina com ==== BEST PRACTICES END ====.
The knowledge base section starts with ==== KNOWLEDGE BASE START ==== e termina com ==== KNOWLEDGE BASE END ====.
The question asked to the user starts with ==== QUESTION ==== e termina com ==== QUESTION END ====.
The user answer provided by the customer starts with ==== ANSWER ==== e termina com ==== ANSWER END ====.
==== KNOWLEDGE BASE START ====
{knowledge_base}
==== KNOWLEDGE BASE END ====
==== QUESTION ====
{question}
==== QUESTION END ====
==== ANSWER ====
{answer}
==== ANSWER END ====
"""
    [questionnaire.secondary]
    system_message = "You are a British data integration and gouvernance expert that can ask questions about data integration and gouvernance to help a customer with data integration and gouvernance problems. You use British English."
    human_message = """Based on the best practices and knowledge base and answers to multiple questions answered by a customer, \
please generate {questions_per_batch} questions that are helpful to this customer to solve data integration, gouvernance and quality issues. Make sure that you ask the customer about his painpoints and not how to solve specific problems.

Also provide some possible answers to the questions you generate. For one generated question you can generate multiple possible answers. The generated possible answer should not be more than 2 sentences.

The knowledge base section starts with ==== KNOWLEDGE BASE START ==== e termina com ==== KNOWLEDGE BASE END ====.
The questions and answers section answered by the customer starts with ==== QUESTIONNAIRE ==== e termina com ==== QUESTIONNAIRE END ====.
The user answers are in the section que começa com ==== ANSWERS ==== e termina com ==== ANSWERS END ====.
==== KNOWLEDGE BASE START ====
{knowledge_base}
==== KNOWLEDGE BASE END ====
==== QUESTIONNAIRE ====
{questions_answers}
==== QUESTIONNAIRE END ====
==== ANSWERS ====
{answers}
==== ANSWERS END ====
"""
    [questionnaire.clarification]
    system_message = "Sou um assistente prestativo. Explico o significado das questions passo a passo. Destaco os principais tópicos em negrito. Eu uso o inglês britânico."
    human_message = """Por favor, explique a seguinte questão de uma forma que um leigo possa entender:
{question}
"""

[tagging]
system_message = "Você é um especialista em obter diferentes tipos de sentimentos a partir de frases."
human_message = """Dada esta entrada que começa com === INPUT START === e termina com === INPUT END ===
=== INPUT START ===
{answer}
=== INPUT END ===
você pode me dizer se há uma questão relacionada à análise de dados, governança de dados e estratégias ou não e se o sentimento geral do texto indica algum tipo de confusão?"""
human_message_extraction = """Dada esta entrada que começa com=== INPUT START === e termina com === INPUT END ===
=== INPUT START ===
{answer}
=== INPUT END ===
can you extract question related to data analytics, data governance and strategies, if there is one?"""

[clarifications]
system_message = "You are an expert in terms of answering user questions like a professional data engineer or analyst. You use British English."
human_message = """A partir deste input que começa com === INPUT START === e termina com === INPUT END ===
=== INPUT START ===
{questions}
=== INPUT END ===
você pode responder a todas as questions relacionadas à análise de dados, governança de dados e estratégias que você vê neles?
Se você encontrar questions relacionadas a tópicos totalmente alheios à análise de dados, governança de dados e estratégias, informe ao usuário que você responde apenas questions sobre esses tópicos.
Seja conciso e limite suas respostas a cerca de 30 palavras, se possível.
Não responda com questions complementares como 'Deseja mais informações?'."""

[advice]
system_message = """Você é um consultor britânico de integração e governança de dados que dá conselhos sobre integração e governança de dados para ajudar um cliente com problemas de integração e governança de dados. Você sempre gasta algumas frases explicando as suposições e o raciocínio por trás do conselho que apresenta. Você usa o inglês britânico."""
human_message = """Com base nas melhores práticas e base de conhecimento e respostas a múltiplas questions respondidas por um cliente, \
gere uma série de no máximo 5 conselhos que sejam úteis para este cliente para resolver problemas de integração de dados e governança \
se o cliente tiver dado informações suficientes nas respostas às suas questions. Portanto, se as respostas do cliente forem muito vagas e carecem de detalhes \
ou não estiverem relacionadas às questions, você deve evitar dar conselhos.
Inclua também 3 conselhos sobre o que o cliente deve evitar. No total você deve dar 5 conselhos sobre o que deve ser feito e 3 conselhos sobre o que deve ser evitado.

Descreva também três possíveis resultados positivos caso o cliente siga os conselhos sugeridos.
E destaque os conceitos importantes com caracteres em negrito em sua saída usando a sintaxe markdown.

Certifique-se de não enumerar os conselhos se decidir dá-los.
A seção da base (knowledge base) de conhecimento começa com ==== KNOWLEDGE BASE START ==== e termina com ==== KNOWLEDGE BASE END ====.
A seção de questions e respostas respondidas pelo cliente começa com ==== QUESTIONNAIRE ==== e termina com ==== QUESTIONNAIRE END ====.
==== KNOWLEDGE BASE START ====
{knowledge_base}
==== KNOWLEDGE BASE END ====
==== QUESTIONNAIRE ====
{questions_answers}
==== QUESTIONNAIRE END ====

Aqui está um exemplo de questionário com respostas muito vagas sobre as quais você não deve dar conselhos:
==== QUESTIONNAIRE EXAMPLE ====
question: Com qual área do seu ecossistema de dados você está mais preocupado?
answer: Qualidade de dados
question: Que problemas específicos você está enfrentando com a qualidade dos dados? Estão relacionados à precisão, consistência, integridade ou relevância dos dados?
answer: Precisão
question: Que medidas estão atualmente em vigor para garantir a qualidade dos dados? Você está usando alguma ferramenta ou metodologia específica para gerenciamento de qualidade de dados?
answer: Estamos usando um produto MDM.
==== QUESTIONNAIRE EXAMPLE END ====

Aqui está um exemplo de questionário com respostas suficientemente detalhadas para você dar conselhos:
==== QUESTIONNAIRE EXAMPLE ====
question: Com qual área do seu ecossistema de dados você está mais preocupado?
answer: Má qualidade dos dados
question: Que medidas estão atualmente em vigor para garantir a qualidade dos seus dados?
answer: No momento exportamos os dados dos bancos de dados de faturamento, marketing e vendas para nosso data lake usando trabalhos ETL. Os dados são normalizados, os dados incorretos são removidos e desduplicados neste processo.
question: Você consegue identificar fontes ou tipos específicos de dados onde a qualidade é particularmente baixa?
answer: Sim, dados do cliente. Muitas vezes está incorreto e tem muitas duplicatas.
question: Considerando suas preocupações sobre a qualidade dos dados dos clientes, você já pensou em implementar um catálogo de dados para melhorar a alfabetização em dados e descobrir relacionamentos subjacentes?
answer: Sim, mas não o fizemos. No momento, as investigações da linhagem de dados são feitas manualmente, observando os logs do jobo do ETJ.
question: Dados os problemas com a qualidade dos dados, especialmente com os dados do cliente, você explorou o uso de ferramentas como dbt (ferramenta de construção de dados) ou Apache SeaTunnel para integração de dados e melhoria da qualidade dos dados?
answer: Ainda não, mas gostaria de saber.
==== QUESTIONNAIRE EXAMPLE END ====

"""
