name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@main
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
       
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.2
        virtualenvs-create: true
        virtualenvs-in-project: true
        virtualenvs-path: ~/.venv
        installer-parallel: true
    - name: poetry-chainlit
      run: |
        # conda install poetry
        # stop the build if there are Python syntax errors or undefined names
        poetry install --sync
        poetry add --editable ./wheels/chainlit-0.7.8.10-py3-none-any.whl
    - name: RUN
      run: |   
        
        python ./data_questionnaire_agent/config.py
        python ./data_questionnaire_agent/utils/tracker_db_init.py
        chainlit run ./data_questionnaire_agent/ui/data_questionnaire_chainlit.py --port 8080
        
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
